name: Run Tests on addingNewGitCommands

on:
  push:
    branches:
      - addingNewGitCommands
  pull_request:
    branches:
      - addingNewGitCommands

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Edge browser
        uses: browser-actions/setup-edge@v1
        with:
          channel: 'stable'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn clean test -DexecutionType=headless


